import os
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.pagesizes import A4
from datetime import datetime
import uuid



REPORT_DIR = "reports"
os.makedirs(REPORT_DIR, exist_ok=True)

def generate_clinical_report(data):
    """
    data: dict containing lesion, classification, cancer_risk info
    returns: path to generated PDF
    """

    report_id = str(uuid.uuid4())[:8]
    filename = f"Clinical_Report_{report_id}.pdf"
    filepath = os.path.join(REPORT_DIR, filename)

    doc = SimpleDocTemplate(filepath, pagesize=A4)
    styles = getSampleStyleSheet()
    content = []

    # ---------- HEADER ----------
    content.append(Paragraph("<b>Clinical Image Analysis Report</b>", styles["Title"]))
    content.append(Spacer(1, 12))

    content.append(Paragraph(
        f"Report ID: {report_id}<br/>"
        f"Generated On: {datetime.now().strftime('%d-%m-%Y %H:%M')}",
        styles["Normal"]
    ))
    content.append(Spacer(1, 20))

    # ---------- LESION INFO ----------
    lesion = data.get("lesion", {})
    content.append(Paragraph("<b>Lesion Analysis</b>", styles["Heading2"]))
    content.append(Spacer(1, 8))

    content.append(Paragraph(
        f"Lesion Status: {lesion.get('label', 'N/A')}<br/>"
        f"Confidence: {lesion.get('confidence', 'N/A')}",
        styles["Normal"]
    ))
    content.append(Spacer(1, 12))

    # ---------- CLASSIFICATION ----------
    dense = data.get("dense", {})
    content.append(Paragraph("<b>Lesion Classification</b>", styles["Heading2"]))
    content.append(Spacer(1, 8))

    content.append(Paragraph(
        f"Predicted Type: {dense.get('label', 'N/A')}<br/>"
        f"Confidence: {dense.get('confidence', 'N/A')}",
        styles["Normal"]
    ))
    content.append(Spacer(1, 12))

    # ---------- CANCER RISK ----------
    risk = data.get("cancer_risk")
    if risk:
        content.append(Paragraph("<b>Cancer Risk Assessment</b>", styles["Heading2"]))
        content.append(Spacer(1, 8))

        content.append(Paragraph(
            f"Cancer Risk Level: {risk.get('risk_label')}<br/>"
            f"Risk Probability: {risk.get('risk_probability')}<br/>"
            f"Tumor Growth (Relative): {risk.get('tumor_growth_relative')}<br/>"
            f"Estimated Tumor Size: {risk.get('estimated_size_mm')} mm",
            styles["Normal"]
        ))
        content.append(Spacer(1, 12))

        # ---------- INTERPRETATION ----------
        content.append(Paragraph("<b>Clinical Interpretation</b>", styles["Heading2"]))
        content.append(Spacer(1, 8))

        interpretation = (
            "The detected lesion is classified as a tumor. "
            "Based on visual characteristics such as size and structural patterns, "
            "the estimated cancer risk level has been assessed. "
            "This assessment is intended to support clinical decision-making."
        )

        content.append(Paragraph(interpretation, styles["Normal"]))
        content.append(Spacer(1, 20))

    # ---------- DISCLAIMER ----------
    content.append(Paragraph("<b>Disclaimer</b>", styles["Heading2"]))
    content.append(Spacer(1, 8))

    content.append(Paragraph(
        "This report is generated by an AI-based image analysis system and is "
        "intended for research and decision-support purposes only. "
        "It should not be used as a substitute for professional medical diagnosis.",
        styles["Italic"]
    ))

    doc.build(content)
    return filepath
